name: MCWebMap
main: me.ArchWizard7.MCWebMap.Main
version: 1.0
api-version: 1.20
commands:
  mcwebmap:
    aliases:
      - mwm
      - map
  waypoint:
    usage: "§d/waypoint <dimension> <x> <y> <z> [icon] [display name]"
  test-command:
    usage: "hogehoge"